### ISSUE TITLE
sql formatter 추가

### ISSUE THREAD

**Issue by jongwoo328** [jongwoo328/mytools#4]

**Comment by ohdnf** [comment]
안녕하세요! 해당 기능을 기대하고 있는 예비 사용자입니다 :)
혹시 아래 세부 기능이 추가될 수 있는지 문의드립니다!

- 입력된 SQL문이 유효한지 검사하여 유효하지 않은 Syntax일 경우 에러 반환 등
- 입력된 [Reserved words](https://www.sqlstyle.guide/#reserved-keyword-reference)를 대소문자로 변환(예: `select * from user` → `SELECT * FROM user` 또는 `SELECT * FROM user` → `select * from user`)

**Comment by jongwoo328** [comment]
@ohdnf  안녕하세요. 내부적으로 [sql-formatter](https://github.com/sql-formatter-org/sql-formatter) 라이브러리를 사용 예정이며 
두 기능 모두 지원할 예정입니다.
라이브러리 기능을 사용하기 때문에 유효성 검사는 SQL문을 실행 가능한지 여부가 아닌 잘못된 토큰이 있는지 여부로 판단 될 예정입니다.
ex) 
`select id` : (O) -> 미완성이지만 잘못된 토큰이 없음
`select !` : (X) -> 컬럼 첫 글자로 !가 올 수 없음 (unexpected token)이므로 유효하지 않음
