### ISSUE TITLE
SQL Formatter 예약어(Keyword) 대소문자 적용

### ISSUE THREAD

**Issue by ohdnf** [jongwoo328/mytools#77]
### 발생 이슈
- [SQL Formatter](https://tools.jongwoo.me/formatter/sql)의 Keyword를 "Upper"로 설정하고 포맷팅을 진행할 경우 일부 예약어(`asc`, `desc`)가 변경되지 않습니다.
- 라이브러리 자체 이슈인 것으로 보입니다.
- MacOS, Chrome Browser에서 실행하였습니다.
### 재현
1. 하기와 같이 SQL 입력
```sql
select * from customers as c left join orders as o on c.id = o.customer_id where c.status = 'done' order by c.created_at desc, o.created_at asc
```
2. Format을 눌렀을 때 결과값에서 일부 예약어가 변경되지 않음을 확인할 수 있습니다.
```sql
SELECT
  *
FROM
  customers AS c
  LEFT JOIN orders AS o ON c.id = o.customer_id
WHERE
  c.status = 'done'
ORDER BY
  c.created_at desc,
  o.created_at asc
```

**Comment by jongwoo328** [comment]
오른쪽 위 드롭다운에서 MySQL 또는 MariaDB를 선택하고 해보세요
