### ISSUE TITLE
GitHub URL 링크 추가

### ISSUE THREAD

**Issue by ohdnf** [jongwoo328/mytools#9]
안녕하세요 ㅎㅎ SQL Formatter 잘 쓰고 있습니다.

[My Tools 사이트](https://tools.jongwoo.me/) 상단 네비게이션바에 본 GitHub Repository로 이동할 수 있는 링크가 있었으면 좋겠습니다. 개선사항 생각나는 것들 Issue로 생성할 수 있을 것 같아서요 ;)

**Comment by jongwoo328** [comment]
부끄러워서 안넣습니다
